### ISSUE TITLE
Data Availability

### ISSUE THREAD

**Issue by m-chang3** [niaid/irae_manuscript#1]
Hi,
I am unable to find the starting data and it isn't downloaded when I download the repo. In the instructions, it simply says "download starting data and add the /data folder directly to the root directory containing the .Rproj file" but doesn't specify where to download the starting data. Can you please clarify?
Thanks!

**Comment by MattPM** [comment]
Hi @m-chang3 stay tuned, data will be available on publication of the preprint. 
Cheers,
-Matt
